version: '3.8'
services:
  application:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0
      - LIBGL_ALWAYS_INDIRECT=true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    stdin_open: true
    tty: true
    ports:
      - "5900:5900" # Expose VNC port for GUI access if needed
