name: Scala CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./echo-relics

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Debug Git State
      run: |
        echo "Checking Git status..."
        git status
        echo "Checking Git log..."
        git log -1
        echo "Checking HEAD ref..."
        git rev-parse HEAD
        echo "Checking branch name..."
        git rev-parse --abbrev-ref HEAD

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Run compile
      run: sbt compile

    - name: Run tests
      run: sbt test

    - name: Cache SBT
      uses: actions/cache@v4
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}


  run_tests:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./echo-relics

    steps:
      - uses: actions/checkout@v4

      - name: export Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
        run: |
          export CI_BRANCH="${GITHUB_REF#refs/heads/}"
          sbt clean coverage test coverageReport coveralls
