name: Scala CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Git checkout (merge)
            uses: actions/checkout@v4
            if: github.event_name != 'pull_request'
            with:
              fetch-depth: 0

          - name: Git checkout (PR)
            uses: actions/checkout@v4
            if: github.event_name == 'pull_request'
            with:
              fetch-depth: 0
              ref: ${{ github.event.pull_request.head.sha }}

          - name: Run tests
            run: sbt clean coverage test

          - name: Upload coverage data to Coveralls
            run: sbt coverageReport coveralls
            env:
              COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
